In [3]:
import pandas as pd

In [4]:
bios_df = pd.read_csv("athletes/bios.csv")

In [5]:
bios_df.head()

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",Toto,NaN,NaN,NaN,NaN,NaN
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
bios_df.head(2)

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN

**Things to clean:**
- [x] Finished task
- [x] Get rid of bullet points in used Names
- [x] Split height/weight
- [x] Parse out dates from `Born` & `Died` column
- [ ] Parse out city, region, and country from `Born` column
- [ ] Get rid of extra columns

In [7]:
df = bios_df.copy()

In [8]:
type(bios_df)

pandas.DataFrame

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 16 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Roles          145500 non-null  str
 1   Sex            145500 non-null  str
 2   Full name      145500 non-null  str
 3   Used name      145500 non-null  str
 4   Born           143772 non-null  str
 5   Died           34042 non-null   str
 6   NOC            145499 non-null  str
 7   athlete_id     145500 non-null  int64
 8   Measurements   107833 non-null  str
 9   Affiliations   95832 non-null   str
 10  Nick/petnames  9145 non-null    str
 11  Title(s)       399 non-null     str
 12  Other names    7167 non-null    str
 13  Nationality    8259 non-null    str
 14  Original name  30739 non-null   str
 15  Name order     7844 non-null    str
dtypes: int64(1), str(15)
memory usage: 41.2 MB

**Used name column**

In [10]:
df['name'] = df["Used name"].str.replace("•"," ")

In [11]:
df.head(3)

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,name
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Jean-François Blanchy
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,Arnaud Boetsch
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN,Jean Borotra

**Split the measurements column into height and weight cols**

In [12]:
df['Measurements'].str.split("/",expand=True)

              0       1
0           NaN     NaN
1       183 cm    76 kg
2       183 cm    76 kg
3       168 cm    64 kg
4           NaN     NaN
...         ...     ...
145495  167 cm    61 kg
145496  168 cm    65 kg
145497  163 cm    55 kg
145498   166 cm     NaN
145499      NaN     NaN

[145500 rows x 2 columns]

In [13]:
#df.drop(columns=['height','weight'], inplace=True)

In [14]:
df[['height_cm','weight_kg']]=  df['Measurements'].str.split("/",expand=True)

#### 1. Check to make sure all the values have the '/'
#### 2. Get rid of 'cm' and the 'kg' from our new columns

*1*

In [15]:
df[~df['Measurements'].str.contains('/',na=True)]

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,name,height_cm,weight_kg
87,Competed in Olympic Games • Non-starter,Male,"Hugh Lawrence ""Laurie""•Doherty",Laurie•Doherty,"8 October 1875 in Wimbledon, England (GBR)","21 August 1919 in Broadstairs, England (GBR)",Great Britain,88,178 cm,"All England Lawn Tennis and Croquet Club, Wimb...",Little Do,NaN,NaN,NaN,NaN,NaN,Laurie Doherty,178 cm,NaN
105,Competed in Olympic Games,Male,Harold Segerson•Mahony,Harold•Mahony,"13 February 1867 in Edinburgh, Scotland (GBR)","27 June 1905 in between Glencar and Killorgin,...",Great Britain,106,191 cm,"Fitzwilliam Lawn Tennis Club, Dublin (IRL)",NaN,NaN,NaN,Ireland,NaN,NaN,Harold Mahony,191 cm,NaN
165,Competed in Olympic Games,Female,Patricia Akosua•Offel,Patricia•Offel,19 December 1971,NaN,Ghana,166,120 kg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Patricia Offel,120 kg,NaN
242,Competed in Olympic Games,Female,"Lucia Francisca ""Susy""•Susanti Haditono",Susy•Susanti,"11 February 1971 in Tasikmalaya, Jawa Barat (INA)",NaN,Indonesia,243,161 cm,"Jaya Raya, Jakarta (INA)",NaN,NaN,"Wang Lianxiang, 王蓮香",NaN,NaN,NaN,Susy Susanti,161 cm,NaN
243,Competed in Olympic Games,Female,Lili•Tampi,Lili•Tampi,"19 May 1970 in Tasikmalaya, Jawa Barat (INA)",NaN,Indonesia,244,161 cm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Lili Tampi,161 cm,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145058,Competed in Olympic Games,Male,Daniil Ruslanovich•Serokhvostov,Daniil•Serokhvostov,"4 April 1999 in Barnaul, Altay Kray (RUS)",NaN,ROC,148770,168 cm,NaN,NaN,NaN,NaN,NaN,Даниил Русланович•Серохвостов,NaN,Daniil Serokhvostov,168 cm,NaN
145096,Competed in Olympic Games,Female,Kamila Valeryevna•Valiyeva,Kamila•Valiyeva,"26 April 2006 in Kazan, Respublika Tatarstan (...",NaN,ROC,148809,160 cm,NaN,NaN,NaN,NaN,NaN,Камила Валерьевна•Валиева,NaN,Kamila Valiyeva,160 cm,NaN
145163,Competed in Olympic Games,Male,Daniel Andrei•Cacina,Daniel Andrei•Cacina,"17 October 2001 in Brașov, Brașov (ROU)",NaN,Romania,148880,190 cm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Daniel Andrei Cacina,190 cm,NaN
145494,Competed in Olympic Games,Male,George Fletcher•Wright,George•Wright,"21 July 1890 in Toronto, Ontario (CAN)","28 January 1973 in Los Angeles, California (USA)",Canada,149221,183 cm,"Argonaut Rowing Club, Toronto (CAN)",NaN,NaN,NaN,NaN,NaN,NaN,George Wright,183 cm,NaN
145498,Competed in Olympic Games,Male,André•Foussard,André•Foussard,"19 May 1899 in Niort, Deux-Sèvres (FRA)","18 March 1986 in Niort, Deux-Sèvres (FRA)",France,149225,166 cm,"Beauvoisine FC, Rouen (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,André Foussard,166 cm,NaN

In [16]:
len(df)

145500

In [17]:
df['Measurements'].str.contains('/').sum()

103028

*example dataset*

In [18]:
small_data = pd.DataFrame(['180 cm', '185 cm / 150 kg', '192 cm / 85kg','105kg'], columns=["Measurements"])
small_data[['height_cm','weight_kg']]=  small_data['Measurements'].str.split("/",expand=True)

small_data['weight_kg'].fillna(small_data['height_cm'],inplace=True)

small_data['height_cm'] = pd.to_numeric(small_data['height_cm'].str.strip(" cm"), errors='coerce')
small_data['weight_kg'] = pd.to_numeric(small_data['weight_kg'].str.strip(" kg"), errors='coerce')

small_data

C:\Users\makge\AppData\Local\Temp\ipykernel_25636\3452179335.py:4: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  small_data['weight_kg'].fillna(small_data['height_cm'],inplace=True)

      Measurements  height_cm  weight_kg
0           180 cm      180.0        NaN
1  185 cm / 150 kg      185.0      150.0
2    192 cm / 85kg      192.0       85.0
3            105kg        NaN        NaN

In [19]:
small_data.dtypes

Measurements        str
height_cm       float64
weight_kg       float64
dtype: object

*2*

In [20]:
df.head(2)

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,name,height_cm,weight_kg
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Jean-François Blanchy,NaN,NaN
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,Arnaud Boetsch,183 cm,76 kg

In [21]:
df['weight_kg'].fillna(df['height_cm'],inplace=True)

df['height_cm'] = pd.to_numeric(df['height_cm'].str.strip(" cm"), errors='coerce')
df['weight_kg'] = pd.to_numeric(df['weight_kg'].str.strip(" kg"), errors='coerce')
df

C:\Users\makge\AppData\Local\Temp\ipykernel_25636\2280672320.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['weight_kg'].fillna(df['height_cm'],inplace=True)

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,name,height_cm,weight_kg
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Jean-François Blanchy,NaN,NaN
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,Arnaud Boetsch,183.0,76.0
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN,Jean Borotra,183.0,76.0
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",Toto,NaN,NaN,NaN,NaN,NaN,Jacques Brugnon,168.0,64.0
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,Albert Canet,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145495,Competed in Olympic Games,Female,Polina•Luchnikova,Polina•Luchnikova,"30 January 2002 in Serov, Sverdlovsk (RUS)",NaN,ROC,149222,167 cm / 61 kg,"Agidel, Ufa (RUS)",NaN,NaN,NaN,NaN,NaN,NaN,Polina Luchnikova,167.0,61.0
145496,Competed in Olympic Games,Female,Valeriya Sergeyevna•Merkusheva,Valeriya•Merkusheva,"20 September 1999 in Moskva (Moscow), Moskva (...",NaN,ROC,149223,168 cm / 65 kg,"SKIF Nizhny Novgorod, Nizhny Novgorod (RUS)",NaN,NaN,NaN,NaN,Валерия Сергеевна•Меркушева,NaN,Valeriya Merkusheva,168.0,65.0
145497,Competed in Olympic Games,Female,Yuliya•Smirnova,Yuliya•Smirnova,"8 May 1998 in Kotlas, Arkhangelsk (RUS)",NaN,ROC,149224,163 cm / 55 kg,"Agidel, Ufa (RUS)",NaN,NaN,NaN,NaN,Юлия•Смирнова,NaN,Yuliya Smirnova,163.0,55.0
145498,Competed in Olympic Games,Male,André•Foussard,André•Foussard,"19 May 1899 in Niort, Deux-Sèvres (FRA)","18 March 1986 in Niort, Deux-Sèvres (FRA)",France,149225,166 cm,"Beauvoisine FC, Rouen (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,André Foussard,166.0,NaN
145499,Non-starter • Administrator,Male,"William Berge ""Bill""•Phillips",Bill•Phillips,"15 July 1913 in Dulwich Hill, New South Wales ...","20 October 2003 in Sydney, New South Wales (AUS)",Australia,149814,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bill Phillips,NaN,NaN

In [22]:
df[~df['Measurements'].str.contains("/",na=True)]

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order,name,height_cm,weight_kg
87,Competed in Olympic Games • Non-starter,Male,"Hugh Lawrence ""Laurie""•Doherty",Laurie•Doherty,"8 October 1875 in Wimbledon, England (GBR)","21 August 1919 in Broadstairs, England (GBR)",Great Britain,88,178 cm,"All England Lawn Tennis and Croquet Club, Wimb...",Little Do,NaN,NaN,NaN,NaN,NaN,Laurie Doherty,178.0,NaN
105,Competed in Olympic Games,Male,Harold Segerson•Mahony,Harold•Mahony,"13 February 1867 in Edinburgh, Scotland (GBR)","27 June 1905 in between Glencar and Killorgin,...",Great Britain,106,191 cm,"Fitzwilliam Lawn Tennis Club, Dublin (IRL)",NaN,NaN,NaN,Ireland,NaN,NaN,Harold Mahony,191.0,NaN
165,Competed in Olympic Games,Female,Patricia Akosua•Offel,Patricia•Offel,19 December 1971,NaN,Ghana,166,120 kg,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Patricia Offel,NaN,NaN
242,Competed in Olympic Games,Female,"Lucia Francisca ""Susy""•Susanti Haditono",Susy•Susanti,"11 February 1971 in Tasikmalaya, Jawa Barat (INA)",NaN,Indonesia,243,161 cm,"Jaya Raya, Jakarta (INA)",NaN,NaN,"Wang Lianxiang, 王蓮香",NaN,NaN,NaN,Susy Susanti,161.0,NaN
243,Competed in Olympic Games,Female,Lili•Tampi,Lili•Tampi,"19 May 1970 in Tasikmalaya, Jawa Barat (INA)",NaN,Indonesia,244,161 cm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Lili Tampi,161.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145058,Competed in Olympic Games,Male,Daniil Ruslanovich•Serokhvostov,Daniil•Serokhvostov,"4 April 1999 in Barnaul, Altay Kray (RUS)",NaN,ROC,148770,168 cm,NaN,NaN,NaN,NaN,NaN,Даниил Русланович•Серохвостов,NaN,Daniil Serokhvostov,168.0,NaN
145096,Competed in Olympic Games,Female,Kamila Valeryevna•Valiyeva,Kamila•Valiyeva,"26 April 2006 in Kazan, Respublika Tatarstan (...",NaN,ROC,148809,160 cm,NaN,NaN,NaN,NaN,NaN,Камила Валерьевна•Валиева,NaN,Kamila Valiyeva,160.0,NaN
145163,Competed in Olympic Games,Male,Daniel Andrei•Cacina,Daniel Andrei•Cacina,"17 October 2001 in Brașov, Brașov (ROU)",NaN,Romania,148880,190 cm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Daniel Andrei Cacina,190.0,NaN
145494,Competed in Olympic Games,Male,George Fletcher•Wright,George•Wright,"21 July 1890 in Toronto, Ontario (CAN)","28 January 1973 in Los Angeles, California (USA)",Canada,149221,183 cm,"Argonaut Rowing Club, Toronto (CAN)",NaN,NaN,NaN,NaN,NaN,NaN,George Wright,183.0,NaN
145498,Competed in Olympic Games,Male,André•Foussard,André•Foussard,"19 May 1899 in Niort, Deux-Sèvres (FRA)","18 March 1986 in Niort, Deux-Sèvres (FRA)",France,149225,166 cm,"Beauvoisine FC, Rouen (FRA)",NaN,NaN,NaN,NaN,NaN,NaN,André Foussard,166.0,NaN

**Parse out dates from `Born` & `Died` column**

In [23]:
pattern_reg = r'(\d+ \w+ \d{4}|\d{4})'
df['born_date'] = df['Born'].str.extract(pattern_reg)
df['born_date'] = pd.to_datetime(df['born_date'],format="mixed",errors='coerce')
df['born_year'] = df.born_date.dt.year

df['died_date'] = df['Died'].str.extract(pattern_reg)
df['died_date'] = pd.to_datetime(df['died_date'],format="mixed",errors='coerce')

In [24]:
df.head(2)

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,...,Other names,Nationality,Original name,Name order,name,height_cm,weight_kg,born_date,born_year,died_date
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,...,NaN,NaN,NaN,NaN,Jean-François Blanchy,NaN,NaN,1886-12-12,1886.0,1960-10-02
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",...,NaN,NaN,NaN,NaN,Arnaud Boetsch,183.0,76.0,1969-04-01,1969.0,NaT

In [25]:
df[df['Full name'] == 'Pantelis•Papadopoulos']

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,...,Other names,Nationality,Original name,Name order,name,height_cm,weight_kg,born_date,born_year,died_date
179,Competed in Olympic Games,Male,Pantelis•Papadopoulos,Pantelis•Papadopoulos,1902,1987,Greece,180,NaN,Lawn Tennis Athens,...,NaN,NaN,Παντελής•Παπαδόπουλος,NaN,Pantelis Papadopoulos,NaN,NaN,1902-01-01,1902.0,1987-01-01

In [26]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 22 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Roles          145500 non-null  str
 1   Sex            145500 non-null  str
 2   Full name      145500 non-null  str
 3   Used name      145500 non-null  str
 4   Born           143772 non-null  str
 5   Died           34042 non-null   str
 6   NOC            145499 non-null  str
 7   athlete_id     145500 non-null  int64
 8   Measurements   107833 non-null  str
 9   Affiliations   95832 non-null   str
 10  Nick/petnames  9145 non-null    str
 11  Title(s)       399 non-null     str
 12  Other names    7167 non-null    str
 13  Nationality    8259 non-null    str
 14  Original name  30739 non-null   str
 15  Name order     7844 non-null    str
 16  name           145500 non-null  str
 17  height_cm      106651 non-null  float64
 18  weight_kg      102070 non-null  float64
 19  born_date      143693 non-null  datetime64[us]
 20  born_year      143693 non-null  float64
 21  died_date      33940 non-null   datetime64[us]
dtypes: datetime64[us](2), float64(3), int64(1), str(16)
memory usage: 49.8 MB

---

**Parse out city, region, and country from `Born` column**

---

In [27]:
df['Born'].head(7)

0          12 December 1886 in Bordeaux, Gironde (FRA)
1               1 April 1969 in Meulan, Yvelines (FRA)
2    13 August 1898 in Biarritz, Pyrénées-Atlantiqu...
3              11 May 1895 in Paris VIIIe, Paris (FRA)
4           17 April 1878 in Wandsworth, England (GBR)
5               13 January 1970 in Amiens, Somme (FRA)
6       27 November 1969 in Ris-Orangis, Essonne (FRA)
Name: Born, dtype: str

In [28]:
location_pattern = r'(\w+), (\w+) \((\w+)\)'
df['Born'].str.extract(location_pattern)

                 0            1    2
0         Bordeaux      Gironde  FRA
1           Meulan     Yvelines  FRA
2              NaN          NaN  NaN
3            VIIIe        Paris  FRA
4       Wandsworth      England  GBR
...            ...          ...  ...
145495       Serov   Sverdlovsk  RUS
145496         NaN          NaN  NaN
145497      Kotlas  Arkhangelsk  RUS
145498         NaN          NaN  NaN
145499         NaN          NaN  NaN

[145500 rows x 3 columns]

In [29]:
location_pattern = r'in ([\w\s-]+), ([\w\s-]+) \((\w+)\)'
df['Born'].str.extract(location_pattern)

                   0                     1    2
0           Bordeaux               Gironde  FRA
1             Meulan              Yvelines  FRA
2           Biarritz  Pyrénées-Atlantiques  FRA
3        Paris VIIIe                 Paris  FRA
4         Wandsworth               England  GBR
...              ...                   ...  ...
145495         Serov            Sverdlovsk  RUS
145496           NaN                   NaN  NaN
145497        Kotlas           Arkhangelsk  RUS
145498         Niort           Deux-Sèvres  FRA
145499  Dulwich Hill       New South Wales  AUS

[145500 rows x 3 columns]

In [30]:
df[['born_city','born_region','born_country']] = df['Born'].str.extract(location_pattern)

In [31]:
df.head()

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,...,Name order,name,height_cm,weight_kg,born_date,born_year,died_date,born_city,born_region,born_country
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,...,NaN,Jean-François Blanchy,NaN,NaN,1886-12-12,1886.0,1960-10-02,Bordeaux,Gironde,FRA
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",...,NaN,Arnaud Boetsch,183.0,76.0,1969-04-01,1969.0,NaT,Meulan,Yvelines,FRA
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",...,NaN,Jean Borotra,183.0,76.0,1898-08-13,1898.0,1994-07-17,Biarritz,Pyrénées-Atlantiques,FRA
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",...,NaN,Jacques Brugnon,168.0,64.0,1895-05-11,1895.0,1978-03-20,Paris VIIIe,Paris,FRA
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",...,NaN,Albert Canet,NaN,NaN,1878-04-17,1878.0,1930-07-25,Wandsworth,England,GBR

In [32]:
df[df['Born'].str.contains('KwaZu',na=False)]

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,...,Name order,name,height_cm,weight_kg,born_date,born_year,died_date,born_city,born_region,born_country
71,Competed in Olympic Games,Female,Clare Jacqueline•Wood,Clare•Wood,"8 March 1968 in Zululand, KwaZulu-Natal (RSA)",NaN,Great Britain,72,175 cm / 65 kg,Southdown Lawn Tennis Club,...,NaN,Clare Wood,175.0,65.0,1968-03-08,1968.0,NaT,Zululand,KwaZulu-Natal,RSA
91,Competed in Olympic Games,Male,Lionel Hunter•Escombe,Lionel•Escombe,"1876 in Natal, KwaZulu-Natal (RSA)","15 October 1914 in Brentford, England (GBR)",Great Britain,92,NaN,NaN,...,NaN,Lionel Escombe,NaN,NaN,1876-01-01,1876.0,1914-10-15,Natal,KwaZulu-Natal,RSA
119,Competed in Olympic Games,Male,John David Patrick•Wheatley,Patrick•Wheatley,"20 January 1899 in Vryheid, KwaZulu-Natal (RSA)","5 November 1967 in Kensington, England (GBR)",Great Britain,120,NaN,NaN,...,NaN,Patrick Wheatley,NaN,NaN,1899-01-20,1899.0,1967-11-05,Vryheid,KwaZulu-Natal,RSA
2090,Competed in Olympic Games,Female,Jill•Börresen,Jill•Börresen,"16 December 1973 in Durban, KwaZulu-Natal (RSA)",NaN,South Africa,2100,170 cm / 57 kg,NaN,...,NaN,Jill Börresen,170.0,57.0,1973-12-16,1973.0,NaT,Durban,KwaZulu-Natal,RSA
2509,Competed in Olympic Games,Male,"Harold Austin ""Harry""•Kitson",Harry•Kitson,"17 June 1874 in Richmond, KwaZulu-Natal (RSA)","30 November 1951 in Umkomaas, KwaZulu-Natal (RSA)",South Africa,2521,NaN,NaN,...,NaN,Harry Kitson,NaN,NaN,1874-06-17,1874.0,1951-11-30,Richmond,KwaZulu-Natal,RSA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132834,Competed in Olympic Games,Male,Devon Myles William•Brown,Myles•Brown,"21 May 1992 in Westville, KwaZulu-Natal (RSA)",NaN,South Africa,135742,188 cm / 80 kg,NaN,...,NaN,Myles Brown,188.0,80.0,1992-05-21,1992.0,NaT,Westville,KwaZulu-Natal,RSA
132838,Competed in Olympic Games,Male,Matthew Mark•Meyer,Matthew•Meyer,"4 March 1998 in Durban, KwaZulu-Natal (RSA)",NaN,South Africa,135746,185 cm / 70 kg,"Action Swim Academy (Durban, RSA)",...,NaN,Matthew Meyer,185.0,70.0,1998-03-04,1998.0,NaT,Durban,KwaZulu-Natal,RSA
137413,Competed in Olympic Games,Male,Keanu Kole•Baccus,Keanu•Baccus,"7 June 1998 in Durban, KwaZulu-Natal (RSA)",NaN,Australia,140770,178 cm,"Western Sydney Wanderers, Sydney (AUS)",...,NaN,Keanu Baccus,178.0,NaN,1998-06-07,1998.0,NaT,Durban,KwaZulu-Natal,RSA
140636,Competed in Olympic Games,Male,Zane Sean•Weir,Zane•Weir,"7 September 1995 in Amanzimtoti, KwaZulu-Natal...",NaN,Italy,144149,NaN,NaN,...,NaN,Zane Weir,NaN,NaN,1995-09-07,1995.0,NaT,Amanzimtoti,KwaZulu-Natal,RSA
143067,Competed in Olympic Games,Male,Rory Mario Trevor•Sabbatini,Rory•Sabbatini,"2 April 1976 in Durban, KwaZulu-Natal (RSA)",NaN,Slovakia,146699,177 cm / 77 kg,NaN,...,NaN,Rory Sabbatini,177.0,77.0,1976-04-02,1976.0,NaT,Durban,KwaZulu-Natal,RSA

In [33]:
df['Born'].str.contains('KwaZu').sum()

148

In [34]:
grouped = df.groupby(df['Sex'])
sd = pd.DataFrame(grouped)
sd

,0,1
0,Female,Roles Sex \ 3...
1,Male,Ro...

In [35]:
grouped = df.groupby(df['Sex']).count()
sd = pd.DataFrame(grouped)
sd

,Roles,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,...,Name order,name,height_cm,weight_kg,born_date,born_year,died_date,born_city,born_region,born_country
Sex,,,,,,,,,,,,,,,,,,,,,
Female,39175,39175,39175,39136,2662,39174,39175,32024,26485,1867,...,3372,39175,31977,30881,39135,39135,2655,28925,28925,28925
Male,106325,106325,106325,104636,31380,106325,106325,75809,69347,7278,...,4472,106325,74674,71189,104558,104558,31285,74184,74184,74184

In [36]:
sd

,Roles,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,...,Name order,name,height_cm,weight_kg,born_date,born_year,died_date,born_city,born_region,born_country
Sex,,,,,,,,,,,,,,,,,,,,,
Female,39175,39175,39175,39136,2662,39174,39175,32024,26485,1867,...,3372,39175,31977,30881,39135,39135,2655,28925,28925,28925
Male,106325,106325,106325,104636,31380,106325,106325,75809,69347,7278,...,4472,106325,74674,71189,104558,104558,31285,74184,74184,74184

### Remove any unnecessary columns

In [37]:
df.columns

Index(['Roles', 'Sex', 'Full name', 'Used name', 'Born', 'Died', 'NOC',
       'athlete_id', 'Measurements', 'Affiliations', 'Nick/petnames',
       'Title(s)', 'Other names', 'Nationality', 'Original name', 'Name order',
       'name', 'height_cm', 'weight_kg', 'born_date', 'born_year', 'died_date',
       'born_city', 'born_region', 'born_country'],
      dtype='str')

In [38]:
columns_to_keep = [ 'athlete_id','name', 'born_date','born_city', 'born_region',
                   'born_country', 'NOC','height_cm', 'weight_kg', 'died_date']

df_clean = df[columns_to_keep]

In [39]:
df_clean.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaT
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [40]:
df_clean.to_csv('clean_data/bios.csv',index=False)

### Now clean the results file

In [41]:
results_df = pd.read_csv('results/results.csv')
results_df.head()

C:\Users\makge\AppData\Local\Temp\ipykernel_25636\1370268764.py:1: DtypeWarning: Columns (0: Nationality) have mixed types. Specify dtype option on import or set low_memory=False.
  results_df = pd.read_csv('results/results.csv')

,Games,Event,Team,Pos,Medal,As,athlete_id,NOC,Discipline,Nationality,Unnamed: 7
0,1912 Summer Olympics,"Singles, Men (Olympic)",NaN,=17,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,NaN
1,1912 Summer Olympics,"Doubles, Men (Olympic)",Jean Montariol,DNS,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,NaN
2,1920 Summer Olympics,"Singles, Men (Olympic)",NaN,=32,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,NaN
3,1920 Summer Olympics,"Doubles, Mixed (Olympic)",Jeanne Vaussard,=8,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,NaN
4,1920 Summer Olympics,"Doubles, Men (Olympic)",Jacques Brugnon,4,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,NaN

In [42]:
results_df.head(2)

,Games,Event,Team,Pos,Medal,As,athlete_id,NOC,Discipline,Nationality,Unnamed: 7
0,1912 Summer Olympics,"Singles, Men (Olympic)",NaN,=17,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,NaN
1,1912 Summer Olympics,"Doubles, Men (Olympic)",Jean Montariol,DNS,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,NaN

In [43]:
results_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 308408 entries, 0 to 308407
Data columns (total 11 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Games        308408 non-null  str
 1   Event        308408 non-null  str
 2   Team         121714 non-null  str
 3   Pos          306583 non-null  str
 4   Medal        44139 non-null   str
 5   As           308408 non-null  str
 6   athlete_id   308408 non-null  int64
 7   NOC          308407 non-null  str
 8   Discipline   308407 non-null  str
 9   Nationality  81 non-null      str
 10  Unnamed: 7   0 non-null       float64
dtypes: float64(1), int64(1), str(9)
memory usage: 53.4 MB

In [44]:
results_df.isna().sum()

Games               0
Event               0
Team           186694
Pos              1825
Medal          264269
As                  0
athlete_id          0
NOC                 1
Discipline          1
Nationality    308327
Unnamed: 7     308408
dtype: int64

In [45]:
results_df.shape

(308408, 11)

**Things to clean:**
- [x] create a new `game_year` and `season`
- [x] clean `Pos` column
- [x] `tied` column from `Pos` 
- [ ] Delete other columns

In [46]:
clean_results = results_df.copy()
clean_results.head(2)

,Games,Event,Team,Pos,Medal,As,athlete_id,NOC,Discipline,Nationality,Unnamed: 7
0,1912 Summer Olympics,"Singles, Men (Olympic)",NaN,=17,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,NaN
1,1912 Summer Olympics,"Doubles, Men (Olympic)",Jean Montariol,DNS,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,NaN

In [47]:
clean_results['Games_year'] = clean_results['Games'].str.extract(r'(\d{4}(?:-\d+)?)')

In [48]:
clean_results['Games_season'] = clean_results['Games'].str.extract(r'\d+\s(\w+)')

In [49]:
clean_results.head(2)

,Games,Event,Team,Pos,Medal,As,athlete_id,NOC,Discipline,Nationality,Unnamed: 7,Games_year,Games_season
0,1912 Summer Olympics,"Singles, Men (Olympic)",NaN,=17,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,NaN,1912,Summer
1,1912 Summer Olympics,"Doubles, Men (Olympic)",Jean Montariol,DNS,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,NaN,1912,Summer

In [50]:
clean_results.info()

<class 'pandas.DataFrame'>
RangeIndex: 308408 entries, 0 to 308407
Data columns (total 13 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Games         308408 non-null  str
 1   Event         308408 non-null  str
 2   Team          121714 non-null  str
 3   Pos           306583 non-null  str
 4   Medal         44139 non-null   str
 5   As            308408 non-null  str
 6   athlete_id    308408 non-null  int64
 7   NOC           308407 non-null  str
 8   Discipline    308407 non-null  str
 9   Nationality   81 non-null      str
 10  Unnamed: 7    0 non-null       float64
 11  Games_year    308408 non-null  str
 12  Games_season  308408 non-null  str
dtypes: float64(1), int64(1), str(11)
memory usage: 61.1 MB

In [51]:
clean_results.iloc[[121776]]

,Games,Event,Team,Pos,Medal,As,athlete_id,NOC,Discipline,Nationality,Unnamed: 7,Games_year,Games_season
121776,1888-89 Zappas Olympic Games,"Rope Climbing, Men ()",NaN,1,NaN,Sotirios Versis,55911,GRE,Artistic Gymnastics (Gymnastics),NaN,NaN,1888-89,Zappas

*`Pos`*

In [52]:
clean_results['Place'] = clean_results['Pos'].str.strip('=')

In [53]:
clean_results[~clean_results['Pos'].str.contains(r'^\d+',na=False)]

,Games,Event,Team,Pos,Medal,As,athlete_id,NOC,Discipline,Nationality,Unnamed: 7,Games_year,Games_season,Place
0,1912 Summer Olympics,"Singles, Men (Olympic)",NaN,=17,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,NaN,1912,Summer,17
1,1912 Summer Olympics,"Doubles, Men (Olympic)",Jean Montariol,DNS,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,NaN,1912,Summer,DNS
2,1920 Summer Olympics,"Singles, Men (Olympic)",NaN,=32,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,NaN,1920,Summer,32
3,1920 Summer Olympics,"Doubles, Mixed (Olympic)",Jeanne Vaussard,=8,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,NaN,1920,Summer,8
5,1996 Summer Olympics,"Singles, Men (Olympic)",NaN,=17,NaN,Arnaud Boetsch,2,FRA,Tennis,NaN,NaN,1996,Summer,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
308313,2022 Winter Olympics,"12.5 kilometres Pursuit, Men (Olympic)",NaN,DNF,NaN,Joscha Burkhalter,148916,SUI,Biathlon,NaN,NaN,2022,Winter,DNF
308350,2022 Winter Olympics,"Ice Hockey, Women (Olympic)",Switzerland,DNS,NaN,Caroline Spies,148940,SUI,Ice Hockey (Ice Hockey),NaN,NaN,2022,Winter,DNS
308360,2022 Winter Olympics,"Ice Hockey, Men (Olympic)",Switzerland,DNS,NaN,Sandro Aeschlimann,148950,SUI,Ice Hockey (Ice Hockey),NaN,NaN,2022,Winter,DNS
308366,2022 Winter Olympics,"Cross, Women (Olympic)",NaN,=13,NaN,Sina Siegenthaler,148956,SUI,Snowboarding (Skiing),NaN,NaN,2022,Winter,13
308406,2022 Winter Olympics,"Giant Slalom, Women (Olympic)",NaN,DNF,NaN,Hilma Lövblom,148985,SWE,Alpine Skiing (Skiing),NaN,NaN,2022,Winter,DNF

In [54]:
len(clean_results[(clean_results['Pos'] == 'DNF') | (clean_results['Pos'] =='DNS')])

16780

In [55]:
clean_results['tied'] = clean_results['Pos'].str.contains('=')

In [56]:
clean_results.head()

,Games,Event,Team,Pos,Medal,As,athlete_id,NOC,Discipline,Nationality,Unnamed: 7,Games_year,Games_season,Place,tied
0,1912 Summer Olympics,"Singles, Men (Olympic)",NaN,=17,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,NaN,1912,Summer,17,True
1,1912 Summer Olympics,"Doubles, Men (Olympic)",Jean Montariol,DNS,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,NaN,1912,Summer,DNS,False
2,1920 Summer Olympics,"Singles, Men (Olympic)",NaN,=32,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,NaN,1920,Summer,32,True
3,1920 Summer Olympics,"Doubles, Mixed (Olympic)",Jeanne Vaussard,=8,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,NaN,1920,Summer,8,True
4,1920 Summer Olympics,"Doubles, Men (Olympic)",Jacques Brugnon,4,NaN,Jean-François Blanchy,1,FRA,Tennis,NaN,NaN,1920,Summer,4,False

In [57]:
clean_results['Pos'].isna().sum()

1825

In [58]:
clean_results['tied'].isna().sum()

0

`Map the Medal column`

In [59]:
clean_results['medal_new'] = clean_results['Medal'].map({'Gold':1,'Silver':2,'Bronze':3})

In [60]:
clean_results['medal_new'].value_counts()

medal_new
3.0    14810
1.0    14783
2.0    14546
Name: count, dtype: int64

*`delete column`*

In [61]:
clean_results.columns

Index(['Games', 'Event', 'Team', 'Pos', 'Medal', 'As', 'athlete_id', 'NOC',
       'Discipline', 'Nationality', 'Unnamed: 7', 'Games_year', 'Games_season',
       'Place', 'tied', 'medal_new'],
      dtype='str')

In [62]:
columns_to_keep = ['Games_year','Games_season','Discipline','Event', 'Team', 'As', 
                   'athlete_id', 'NOC','Place', 'tied', 'medal_new']


df = clean_results[columns_to_keep]

In [63]:
import sys
print(sys.executable)

c:\Users\makge\anaconda33\python.exe

In [64]:
import janitor

In [66]:
df = df.clean_names()

In [67]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 308408 entries, 0 to 308407
Data columns (total 11 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   games_year    308408 non-null  str
 1   games_season  308408 non-null  str
 2   discipline    308407 non-null  str
 3   event         308408 non-null  str
 4   team          121714 non-null  str
 5   as            308408 non-null  str
 6   athlete_id    308408 non-null  int64
 7   noc           308407 non-null  str
 8   place         306583 non-null  str
 9   tied          308408 non-null  bool
 10  medal_new     44139 non-null   float64
dtypes: bool(1), float64(1), int64(1), str(8)
memory usage: 48.0 MB

In [72]:
df['games_year'] = pd.to_datetime(df['games_year'], errors='coerce')
df['games_year'] = df['games_year'].dt.year
df['tied'] = df['tied'].astype(bool)

In [73]:
df.head(2)

,games_year,games_season,discipline,event,team,as,athlete_id,noc,place,tied,medal_new
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",NaN,Jean-François Blanchy,1,FRA,17,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean Montariol,Jean-François Blanchy,1,FRA,DNS,False,NaN

In [74]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 308408 entries, 0 to 308407
Data columns (total 11 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   games_year    308407 non-null  float64
 1   games_season  308408 non-null  str
 2   discipline    308407 non-null  str
 3   event         308408 non-null  str
 4   team          121714 non-null  str
 5   as            308408 non-null  str
 6   athlete_id    308408 non-null  int64
 7   noc           308407 non-null  str
 8   place         306583 non-null  str
 9   tied          308408 non-null  bool
 10  medal_new     44139 non-null   float64
dtypes: bool(1), float64(2), int64(1), str(7)
memory usage: 46.9 MB

In [77]:
df.sort_values('games_year', ascending=False)

,games_year,games_season,discipline,event,team,as,athlete_id,noc,place,tied,medal_new
308407,2022.0,Winter,NaN,"Slalom, Women (Olympic)",NaN,Charlotta Säfvenberg,148986,NaN,24.0,False,NaN
289770,2022.0,Winter,Short Track Speed Skating (Skating),"1,000 metres, Women (Olympic)",NaN,Qu Chunyu,136983,CHN,13.0,False,NaN
275694,2022.0,Winter,Biathlon,"12.5 kilometres Mass Start, Women (Olympic)",NaN,Yuliya Dzhima,128645,UKR,7,False,NaN
306945,2022.0,Winter,Nordic Combined (Skiing),"Large Hill / 10 km, Individual, Men (Olympic)",NaN,Zhao Jiawen,148111,CHN,47.0,False,NaN
306946,2022.0,Winter,Nordic Combined (Skiing),"Team, Men (Olympic)",People's Republic of China,Zhao Jiawen,148111,CHN,10.0,False,NaN
...,...,...,...,...,...,...,...,...,...,...,...
149143,1896.0,Summer,Athletics,"110 metres Hurdles, Men (Olympic)",NaN,Alajos Szokoly,71310,HUN,AC h1 r1/2,False,NaN
69730,1896.0,Summer,Artistic Gymnastics (Gymnastics),"Horse Vault, Men (Olympic)",NaN,Louis Zutter,31059,SUI,2,False,2.0
69731,1896.0,Summer,Artistic Gymnastics (Gymnastics),"Parallel Bars, Men (Olympic)",NaN,Louis Zutter,31059,SUI,2,False,2.0
111835,1896.0,Summer,Athletics,"100 metres, Men (Olympic)",NaN,Harald Arbin,50347,SWE,DNS,False,NaN
121776,NaN,Zappas,Artistic Gymnastics (Gymnastics),"Rope Climbing, Men ()",NaN,Sotirios Versis,55911,GRE,1,False,NaN

In [78]:
df.to_csv('clean_data/results.csv',index=False)